---
- block:
    - name: ping
      ping:
      register: pinged
      failed_when: pinged.failed == True
  rescue:
    - set_fact: var="FAILED"
  always:
    - debug:
      var: result
      verbosity: 2
