---
- block:
    - name: ping
      ping:
      register: pinged
      failed_when: pinged.failed == True
  rescue:
    - set_fact: var="FAILED"
  always:
    - name: Print if pinged
      set_fact: var
