---
- block:
    - name: ping
      ping:
      register: pinged
      failed_when: pinged.failed == True
  rescue:
    - set_fact: pinged="FAILED"
  always:
    - debug:
      var: pinged
      verbosity: 2
