POST http://mo-awx.doxtechno.com/api/v2/job_templates/13/launch/ HTTP/1.1
Content-Type: application/json
Authorization: Basic admin:Gl88jZKaPr8AZpBc0daY

{"extra_vars": {"targets": "mo-app03.doxtechno.com"}}


###
GET http://mo-awx.doxtechno.com/api/v2/jobs/124/ HTTP/1.1
Content-Type: application/json
Authorization: Basic admin:Gl88jZKaPr8AZpBc0daY