- name: Gather hcloud volume infos
  hcloud_volume_info:
    api_token: "{{ hetzner.api_key }}"
  register: output
  tags:
    - create

- set_fact:
    vol_num: "{{ output.hcloud_volume_info|length + 1 }}"
  tags:
    - create

- name: Create a volume
  hcloud_volume:
    name: "vol-{{ vol_num }}"
    server: "{{ target }}"
    size: 10
    api_token: "{{ hetzner.api_key }}"
  register: volume
  tags:
    - create

- name: Create volume folder
  delegate_to: "{{ target }}"
  become: yes
  file:
    path: /media/vol-{{ vol_num }}
    owner: admin
    group: admins
    mode: "0644"
    state: directory
  tags:
    - create

- name: Get filesystem_paths
  delegate_to: "{{ target }}"
  shell:
    cmd: lsblk | awk 'NR == 1 || $4 ~ "10"' | awk '{print $1}' | awk 'END{print}'
  register: file_path
  tags:
    - create

- name: Mount and bind a volume
  delegate_to: "{{ target }}"
  become: yes
  mount:
    path: /media/vol-{{ vol_num }}
    src: "/dev/{{ file_path.stdout }}"
    fstype: ext4
    state: present
  tags:
    - create
