---
- name: Switch on machine
  delegate_to: mo-awx
  hcloud_server:
    api_token: "{{ hetzner.api_key }}"
    name: "{{ ansible_hostname }}"
    server_type: cx11
    state: started
  tags:
    - start-machine
