- name: HostOutOfDiskSpace
  hosts: mo-awx.doxtechno.com
  tasks:
    - name: Create Volume
      include_role:
        name: hcloud
        tasks_from: create-vol.yml
      tags:
        - create

    - name: Delete Volume
      include_role:
        name: hcloud
        tasks_from: delete-all-vol.yml
      tags:
        - delete

    - name: Start machine
      include_role:
        name: hcloud
        tasks_from: start-machine.yml
      tags:
        - start-machine
