---
- name: RabbitMQ
  hosts: "{{ target }}"
  environment:
    http_proxy: "{{ http_proxy_server if (http_proxy_server is defined) else omit }}"
    https_proxy: "{{ http_proxy_server if (http_proxy_server is defined) else omit }}"
    no_proxy: "{{ '127.0.0.1,localhost' if (http_proxy_server is defined) else omit }}"
  tasks:
    - name: Create Publisher
      include_role:
        name: Publisher
        tasks_from: create-publisher.yml
      apply:
        tags:
          - create-publisher

    - name: Create Consumer
      include_role:
        name: Consumer
        tasks_from: create-consumer.yml
      tags:
        - create-consumer

    - name: Delete Publisher
      include_role:
        name: Publisher
        tasks_from: delete-publisher.yml
      tags:
        - create-publisher

    - name: Delete Consumer
      include_role:
        name: Consumer
        tasks_from: create-consumer.yml
      tags:
        - create-consumer
