---
- name: RabbitMQ
  hosts: "{{ target }}"
  tasks:
    - name: Create Publisher
      include_role:
        name: rabbitmq
        tasks_from: create-publisher.yml
        apply:
          tags:
            - create-publisher
      tags:
        - create-publisher

    - name: Create Consumer
      include_role:
        name: rabbitmq
        tasks_from: create-consumer.yml
        apply:
          tags:
            - create-consumer
      tags:
        - create-consumer
    # - name: Delete Publisher
    #   include_role:
    #     name: Publisher
    #     tasks_from: delete-publisher.yml
    #   tags:
    #     - create-publisher
    # - name: Delete Consumer
    #   include_role:
    #     name: Consumer
    #     tasks_from: create-consumer.yml
    #   tags:
    #     - create-consumer
