- name: Target Down
  hosts: "{{ targets }}"
  gather_facts: no
  environment:
    http_proxy: "{{ http_proxy_server if (http_proxy_server is defined) else omit }}"
    https_proxy: "{{ http_proxy_server if (http_proxy_server is defined) else omit }}"
    no_proxy: "{{ '127.0.0.1,localhost' if (http_proxy_server is defined) else omit }}"
  tasks:
    - name: Switch on node_exporter
      include_role:
        name: adhoc
        tasks_from: systemctl_on.yml
