---
- name: System
  hosts: "{{ target }}"
  environment:
    http_proxy: "{{ http_proxy_server if (http_proxy_server is defined) else omit }}"
    https_proxy: "{{ http_proxy_server if (http_proxy_server is defined) else omit }}"
    no_proxy: "{{ '127.0.0.1,localhost' if (http_proxy_server is defined) else omit }}"
  tasks:
    - name: Start service
      become: yes
      systemd:
        name: "{{ item }}"
        state: started
      with_items:
        - "{{ service_name }}"
      tags:
        - start-service

    - name: Stop service
      become: yes
      systemd:
        name: "{{ item }}"
        state: started
      with_items:
        - "{{ service_name }}"
      tags:
        - stop-service
